### PR TITLE
Code mods for multiple disk drives

### PR DESCRIPTION
**Pull request by Trevor-Jacobs**
Files changed by this pull are:
retro/retro.asm
retro/Makefile

New files:
retro/rw_nocache_md.asm
filesystem/retro_multi_disk_prep_notes.txt

Bla Bla

### CODE REVIEW

**Comment by johnwinans** [comment]
Trevor,
I think we got the branching figured out.  Thanks!

Here are the immediate issues in the way of releasing this:
Please keep the whitespace/comment alignment consistent.
We can't allow 4 drives if someone wants to compile in any of the other disk I/O versions.. that only support 1.
Until the other cache options are made compatible, we need the number of drives to dependent on the version of the cache   
logic they chose.  
We also should not define more DPBs than are needed when not building a multi-drive BIOS.

This has to be made configurable.  I want it to all be automatic based on what one decides to compile.

Let me work on it and see what I come up with.

**Comment by johnwinans** [comment]
Other thoughts related to this include making the allocation block size larger. As I have configured the Retro's disks, it is impractical to have an 8MB drive since the ONLY way to use it all would be to create files that each have an exact multiple of 16384 bytes in them.
Increasing the allocation block size will which would reduce the size of the problematic ALVs.
Right now the allocation blocks are 2K.  If we change them to 4K the ALVs shrink by half.  8K they will quarter.  Therefore, if we go to 8K then 16 drives will take the same space as 4, 2K configurations.
I will have to adjust the diskparms used int he building of the filesystems.

What do you think?

**Comment by Trevor-Jacobs** [comment]
Hey John,

I saw the comment alignment too, but it is aligned in my editor here. Github must be translating tabs differently. I always hate that, going from one editor to another it always seems to screw things up. I used to write all my code in DOS Edit or notepad. I’ve been using Geany lately and nano in the cli. I don’t know vim well enough and always mess things up in vim. I should probably learn it though. Seems like a good editor if you know the commands.

Yes, automating multiple drives vs. one drive is probably a good idea. You could just have a separate version of retro.asm called retro_md.asm that assembles at the same time retro.asm does and then you’d end up with retro.bin and retro_md.bin. That way you could choose either binary to run. Not very elegant though. Either way, you have to configure something if you have only one main retro.asm before you run make. I was thinking about this as well, but in the end figured that pretty soon, we’ll have multiple drives as the default when the cache is sorted out. No reason not to have it.

File allocation blocks - if we make them bigger, what is the downside? Larger file sizes for small files? I’m not clear on the relationship between all of the drive components and how they effect each other. I’ll need to read up on that. I was just going by your established drive spec. But, if we can reduce the ALV memory sizes to the point that we can fit 16 8 MB disks in the partition, then I say do it. If there are no real negative side effects. If you want to come up with a new drive spec, I’ll implement it and try it.

How does the code look to you? I’m new to Z80 Assembly but not assembly so hope it’s not too horrible.

Trevor

**Comment by johnwinans** [comment]
It is possible that I changed gears with my editor settings somewhere along the way.  I'll check my own settings and deal with the spacing.

Creating a new retro.bin would crate a mess by replicating too much code.  I am working on adding support for NHACP (a network filesystem) and can see more issues with the API.  Let me get that going and see how it goes.  It too should support multiple drives.  I suspect the solution will be to factor out *all* the DPB junk into the various cache/md libraries.

We will also want to separate the cache support from the disk routines as well so it can all work together.  More mess to untangle. But I think it will be worth it.

Building multiple binaries is an interesting thought as well.  As things get interesting we might have to upgrade to an assembler that supports a link-editor.

Yeah... bigger allocation blocks = courser granularity on disk space usage.

If you look closely at my filesystem design choice. you will notice that the ONLY to use the entire disk is if every directory entry is completely used... which is never going to happen.  So it has to evolve into a more practical config anyway.

More directory entries would be nice but then it takes longer to scan it.

Larger allocation blocks = more wasted disk space. But that is not so much a concern when we have more than any CP/M system has ever had back in the day anyway.  Larger blocks also means that one directory entry represents more space on the disk than with smaller block sizes (also alleviating the directory size problem.)

I always planned a video analyzing the original choices and why I did it -- faster boot times and and easier to understand FCB format... that I also have yet to discuss.)

Lets let this simmer for a while.  I suspect that NHACP and your code needs the same thing.  Let me hack out the DPB stuff from the BIOS and move it into the two cache, NHACP, and md source files.  

In the end, I think we will all want to use the same filesystem format so that the filesystem builds don't get messy.  So I think I will shift that from 2K to 8K or 16K so that we can all get 16 drives.

I expect most of them will be read-only.  I swear that CP/M does not need an ALV if the filesystem is read-only... but I could not find any talk of omitting the ALV.  If you want to read up on the DPH and stuff... see if you can find any official word on that!

**Comment by johnwinans** [comment]
This was hand-integrated into the nhacp branch.
Thank you very much for all your work on this and for your patience needed to complete the task!

**Pull request closed without merging**
